README.md
src/styles/output.css

style: add title + badge readMe

---

src/components/Navbar/NavBar.jsx
src/components/Navbar/components/MenuNav.jsx

fix: when a link is click the menuNavBar close

---

src/Pages/Cart.jsx

fix: the btn proceed to checkout is not display if total price is 0

---

src/components/Navbar/NavBar.jsx
src/components/Navbar/components/MenuNav.jsx

fix: if we click a link in the menu navbar the menu close

---

src/components/Navbar/NavBar.jsx
src/components/Navbar/components/MenuNav.jsx

Now the menu close when we click outside of it when we are in mobile format.
Close #17

UX: when we click outside menu both menu close

---

src/components/Navbar/NavBar.jsx

the navBar is split in 4 function now that all use different hook and made only one thing.
Closes #24

refactor: navBar component is split in multiple function

---

src/components/Home/Carousel.jsx
src/components/Provider/ItemsProvider/ItemsProvider.jsx
src/styles/input.css
src/styles/output.css

fix: get the data of the api and put it in the cache

---

notes.md
test/Carousel.test.jsx
test/navbar.test.jsx

testing the links in the navbar component 
- results - fail

link testing - navbar component

---

src/components/Home/Carousel.jsx
test/Carousel.test.jsx

40 change test carousel

---

src/components/Contact/Forms.jsx

fix: added required to contact form

---

src/components/Home/Shop/components/Card.jsx

fix: remove hover effect on card

---

src/Pages/Cart.jsx
src/components/Home/Shop/components/FilterShop.jsx
src/components/Navbar/NavBar.jsx
src/components/Navbar/components/BtnCart.jsx
src/styles/input.css
src/styles/output.css
tailwind.config.js

fix: change style navbar

---

src/components/Contact/Blob.jsx
src/components/Contact/Forms.jsx
src/styles/output.css

feat: new style for the form

---

src/components/Home/Carousel.jsx
src/styles/output.css

fix: change chevron on caroussel

---

src/components/Cart/CartCard.jsx
src/components/Provider/CartProvider/CartProvider.jsx
src/components/Provider/CartProvider/Hook.jsx
src/styles/output.css

Add a new provider + rewrite the logic of the card Cart

feat: add can choose number of item that we want by writing

---

src/App.jsx
src/Pages/Cart.jsx
src/styles/output.css

proceed to checkout div is in the center when mobile format

feat: proceed to checkout div is in the center when mobile format

---

src/components/Navbar/components/Menucart/MenuCart.jsx
src/styles/input.css
src/styles/output.css

can scroll to the bottom of the cart menu

fix: can scroll to the bottom of the cart menu

---

src/components/Home/Shop/components/Card.jsx

Now we can click on the image to bring to the description

feat: click on the image to bring to the description

---

src/Pages/About.jsx
src/components/Navbar/components/MenuNav/MenuNav.jsx
src/components/Navbar/components/Menucart/MenuCart.jsx
src/styles/input.css
src/styles/output.css

The section is about the brand and the value of it.

feat: add section in About page

---

src/Pages/About.jsx
src/Pages/Product.jsx
src/components/Cart/BtnCartCard.jsx
src/components/GoBackBtn.jsx
src/components/Navbar/components/Menucart/components/CardCart.jsx
src/components/Product/CTAsection.jsx
src/components/Product/RatingStars.jsx
src/styles/output.css

Add : 
- Rating stars
- Better CTA
- +/- button to add item to the cart
- number of rating

Feat: change all design Product page

---

src/components/Cart/CheckoutBtn.jsx
src/styles/output.css

change message in btncheckout depending on the state of the request

feat: when we click checkout btn should display loading

---

src/components/Navbar/components/MenuNav/MenuNav.jsx
src/styles/input.css
src/styles/output.css

 Bug : Navbar Color Change

---

src/Pages/About.jsx
src/Pages/Product.jsx
src/components/About/Accordion.jsx
src/components/Cart/CheckoutBtn.jsx
src/components/Product/DescriptionItem.jsx
src/components/Product/RatingItem.jsx
src/components/Product/RatingStars.jsx
src/components/Product/Reviews/CardReview.jsx
src/components/Product/Reviews/Reviews.jsx
src/styles/output.css

Feat: fake Review in description item
